### ISSUE TITLE
ログイン機能

### ISSUE THREAD

**Issue by Takayyz** [gizumo-oss/yamabico#12]
- [ ] 各画面で認証状態の保持
- [ ] credencialの管理の仕方

**Comment by dorodango-maker** [comment]
https://github.com/wasabeef?tab=repositories

**Comment by koru-soft** [comment]
https://docs.flutter.dev/deployment/flavors
うーん、ちょっと趣旨とは違いそう

**Comment by Takayyz** [comment]
https://dev.classmethod.jp/articles/flutter-dotenv/

> [!warning]
> アプリケーションを公開する場合.envで定義した環境変数は誰でも参照することができます。そのため機密情報を含めることはできません。

注意事項にこれ書いてあるけど、それをどうするか知りたいw

**Comment by Takayyz** [comment]
https://zenn.dev/toridori/articles/20f64bc7972263

難読化や暗号化する方法

**Comment by Takayyz** [comment]
https://zenn.dev/web_tips/books/df8423bbb204a1/viewer/55d8a1

単に`flutter_dotenv`の話だったのでこれはスルーで

**Comment by koru-soft** [comment]
コンパイル時定数の話ですがビルド周りにも触れられてそう
https://itnext.io/flutter-3-7-and-a-new-way-of-defining-compile-time-variables-f63db8a4f6e2

**Comment by iPyone54** [comment]
https://qiita.com/SUGYKEN/items/8837c2394d84b034fe35

**Comment by Takayyz** [comment]
> コンパイル時定数の話ですがビルド周りにも触れられてそう https://itnext.io/flutter-3-7-and-a-new-way-of-defining-compile-time-variables-f63db8a4f6e2

これ使えば`.env`の仕組みを用意する必要がなくなる感じですね。(代わりにjson用意して`flutter run`の時にオプションでjsonファイル指定してやる必要はある)
